name: Cypress Smoke Test

on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: '0 22 * * *'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  ui-chrome-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.6.0-chrome105-ff104
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      
      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v4.2.0
        with:
          install-command: npm install
          wait-on: ${{ secrets.BASE_URL }}
          wait-on-timeout: 120
          browser: chrome
          record: true
          group: 'UI - Chrome'
          spec: cypress/e2e/*
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          config-file: cypress.config.js
          
